In [7]:
import numpy as np
from numpy import random

x = random.randint(45)
x

16

In [6]:
x = random.rand(10)
x

array([0.76047895, 0.14619206, 0.72345275, 0.44895811, 0.02125826,
       0.71147701, 0.72394228, 0.22881857, 0.5437626 , 0.98834183])

In [26]:
x=random.randint(100,size=(3,3))
x



array([[85, 75, 26],
       [ 0, 22, 84],
       [41, 41, 97]])

In [28]:
x= random.rand(3,5)
x

array([[0.77803469, 0.29536715, 0.52876519, 0.11982545, 0.53087345],
       [0.76409503, 0.96308173, 0.85142968, 0.20871933, 0.43293808],
       [0.33101519, 0.73136477, 0.79087478, 0.38400375, 0.02635561]])

In [31]:
x = random.choice([1,2,3,4,5,6,67], size = (3,3))
x 


array([[ 5,  4,  1],
       [ 6,  5,  3],
       [ 5, 67,  6]])

In [67]:
x = random.choice([1,2,3,4,5], p=[0.0,0.1,0.3,0.2,0.4] ,size = (3,3) )
x

array([[5, 5, 3],
       [4, 3, 5],
       [4, 5, 3]])